//FIC: Demo Users Data.
const UsersData = [
    {
      USERID: "FIBARRAC",
      PASSWORD: "1234",
      USERNAME: "FRANCISCO IBARRA CARLOS",
      ALIAS: "Dr.FIC.",
      FIRSTNAME: "FRANCISCO",
      LASTNAME: "IBARRA CARLOS",
      BIRTHDAYDATE: "24.06.1976",
      COMPANYID: 1001,
      COMPANYNAME: "INSTITUTO TECNOLOGICO DE TEPIC",
      COMPANYALIAS: "ITT",
      CEDIID: "IdTepic",
      EMPLOYEEID: "1074",
      EMAIL: "fibarra@ittepic.edu.mx",
      PHONENUMBER: "3111147163",
      EXTENSION: "",
      DEPARTMENT: "Sistemas y Computación",
      FUNCTION: "Catedratico",
      STREET: "Numero conocido 1200",
      POSTALCODE: 63000,
      CITY: "Tepic",
      REGION: "",
      STATE: "Nayarit",
      COUNTRY: "Mexico",
      AVATAR: ""
    },
    {
      USERID: "JLOPEZ",
      PASSWORD: "abcd1234",
      USERNAME: "JUAN LOPEZ HERNANDEZ",
      ALIAS: "Ing.Lopez",
      FIRSTNAME: "JUAN",
      LASTNAME: "LOPEZ HERNANDEZ",
      BIRTHDAYDATE: "15.03.1980",
      COMPANYID: 1002,
      COMPANYNAME: "UNIVERSIDAD AUTONOMA DE MEXICO",
      COMPANYALIAS: "UNAM",
      CEDIID: "IdUNAM",
      EMPLOYEEID: "1088",
      EMAIL: "jlopez@unam.mx",
      PHONENUMBER: "5554321234",
      EXTENSION: "204",
      DEPARTMENT: "Ingeniería",
      FUNCTION: "Profesor",
      STREET: "Av. Universidad 3000",
      POSTALCODE: 504510,
      CITY: "Ciudad de México",
      REGION: "",
      STATE: "CDMX",
      COUNTRY: "Mexico",
      AVATAR: ""
    },
    {
      USERID: "MLARA",
      PASSWORD: "pass5678",
      USERNAME: "MARIA LARA GARCIA",
      ALIAS: "Lic.Lara",
      FIRSTNAME: "MARIA",
      LASTNAME: "LARA GARCIA",
      BIRTHDAYDATE: "02.12.1990",
      COMPANYID: 1003,
      COMPANYNAME: "TEC DE MONTERREY",
      COMPANYALIAS: "ITESM",
      CEDIID: "IdMonterrey",
      EMPLOYEEID: "1099",
      EMAIL: "mlara@itesm.mx",
      PHONENUMBER: "8188885555",
      EXTENSION: "105",
      DEPARTMENT: "Recursos Humanos",
      FUNCTION: "Administradora",
      STREET: "Calle Ficticia 45",
      POSTALCODE: 64000,
      CITY: "Monterrey",
      REGION: "",
      STATE: "Nuevo León",
      COUNTRY: "Mexico",
      AVATAR: ""
    },
    {
      USERID: "RVELAZQUEZ",
      PASSWORD: "rv123",
      USERNAME: "ROBERTO VELAZQUEZ DIAZ",
      ALIAS: "Lic.Velazquez",
      FIRSTNAME: "ROBERTO",
      LASTNAME: "VELAZQUEZ DIAZ",
      BIRTHDAYDATE: "10.07.1985",
      COMPANYID: 1004,
      COMPANYNAME: "UNIVERSIDAD DE GUADALAJARA",
      COMPANYALIAS: "UDG",
      CEDIID: "IdGuadalajara",
      EMPLOYEEID: "1100",
      EMAIL: "rvelazquez@udg.mx",
      PHONENUMBER: "3335678901",
      EXTENSION: "309",
      DEPARTMENT: "Contabilidad",
      FUNCTION: "Contador",
      STREET: "Av. Juárez 123",
      POSTALCODE: 44100,
      CITY: "Guadalajara",
      REGION: "",
      STATE: "Jalisco",
      COUNTRY: "Mexico",
      AVATAR: ""
    },
    {
      USERID: "AGRANADOS",
      PASSWORD: "admin2024",
      USERNAME: "ANA GRANADOS MORA",
      ALIAS: "Mtra.Granados",
      FIRSTNAME: "ANA",
      LASTNAME: "GRANADOS MORA",
      BIRTHDAYDATE: "28.08.1992",
      COMPANYID: 1005,
      COMPANYNAME: "INSTITUTO POLITECNICO NACIONAL",
      COMPANYALIAS: "IPN",
      CEDIID: "IdIPN",
      EMPLOYEEID: "1111",
      EMAIL: "agranados@ipn.mx",
      PHONENUMBER: "5556781234",
      EXTENSION: "",
      DEPARTMENT: "Investigación",
      FUNCTION: "Investigadora",
      STREET: "Calle Ciencias 78",
      POSTALCODE: 807738,
      CITY: "Ciudad de México",
      REGION: "",
      STATE: "CDMX",
      COUNTRY: "Mexico",
      AVATAR: ""
    }
  ];
  
  export default UsersData;
  